# Javascript Node CircleCI 2.0 configuration file.
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

references:
  workspace: &workspace
    ~/repo

  container_config: &container_config
    docker:
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:7.10
    working_directory: *workspace

  win64_config: &win64_config
    docker:
      - image: electronuserland/builder:wine
        environment:
          TARGET_ARCH: x64
    working_directory: *workspace

  mac_config: &mac_config
    machine:
      xcode:
        version: 9.2.0
    working_directory: *workspace

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: sudo yarn global add yarn@1.5.1
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    <<: *container_config
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: sudo yarn global add yarn@1.5.1
      - run: yarn test
    store_artifacts:
      - path: artifacts
      - destination: yarnpkg

  deploy_win64:
    <<: *win64_config
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run: yarn build -w --x64
      - store_artifacts:
          path: dist
          destination: build

  deploy_linux:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: sudo yarn global add yarn@1.5.1
      # - run: apt-get -y update
      # - run: apt-get -y install libusb-1.0-0-dev icnsutils graphicsmagick libudev-dev
      - run: yarn install
      - run: yarn dist
      - store_artifacts:
          path: dist
          destination: build

  deploy_mac:
    <<: *mac_config
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: sudo yarn global add yarn@1.5.1
      - run: yarn install
      - run: yarn dist
      - store_artifacts:
          path: dist
          destination: build

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
  deploy:
    jobs:
      - deploy_win64:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)+.*/
      - deploy_linux:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)+.*/
      - deploy_mac:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)+.*/
